### PR TITLE
Add build-css step to build process

### PR DESCRIPTION
**Pull request by tmoreira2020**

### CODE REVIEW

**Comment by danielreuther** [comment]
Hey Thiago,

Thanks much for sending this!

Just one question, you have put the liferay-plugin-package.properties under an Apache license and I'm not quite sure about that. This very file came into being with the rest of plugin which deliberately uses an attribution to Liferay Inc. and LGPL.

Would you mind moving the attribution to you to an XML comment in pom.xml and removing it from liferay-plugin-package.properties? You definitely deserve to be mentioned, I'm just not sure about that particular file...

Thanks again,
Daniel

**Comment by tmoreira2020** [comment]
Hey Daniel, I just rewrote the commits. Let me know

**Comment by tmoreira2020** [comment]
Hey Daniel, I just rewrote the commits. Let me know.

**Comment by danielreuther** [comment]
Hey Thiago,

Sorry it took so long, I just merged your commits. Thanks so much for your effort!

My Maven knowledge is still pretty basic--so, let me know in case my additional commits don't make sense.

Daniel

**Comment by tmoreira2020** [comment]
Great, everything looks good!

**Pull request merged**
